cc_library(
    name = 'gtest',
    srcs = 'null.cc',
    deps = ['//thirdparty/gtest-1.7.0/:gtest']
)

cc_library(
    name = 'gtest_main',
    srcs = 'null.cc',
    deps = ['//thirdparty/gtest-1.7.0/:gtest_main']
)
