cc_library(name = 'gtest',
           srcs = 'null.cc',
           deps = ['#gtest']
          )

cc_library(name = 'gtest_main',
           srcs = 'null.cc',
           deps = ['#gtest_main']
          )
